server:
  port: 8084

spring:
  application:
    name: gamevault-developer

  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
        group: GAMEVAULT_GROUP
      config:
        enabled: false
        import-check:
          enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

  datasource:
    url: jdbc:postgresql://localhost:12000/gamevault_developer
    username: gamevault_user
    password: gamevault_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
  data:
    redis:
      host: localhost
      port: 12003
      database: 0
      timeout: 2000

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
#  type-aliases-package: com.sg.nusiss.developer.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  asset-base-url: http://localhost:8084
  asset-storage-path: ./gamevault-developer/game-assets
  upload:
    path: uploads
    max-file-size: 1000MB
    max-request-size: 1000MB
  pagination:
    default-page-size: 20
    max-page-size: 100

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.sg.nusiss: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
