services:
  postgres:
    image: postgres:16
    container_name: gamevault_postgres_cloud
    ports:
      - "12000:5432"
    environment:
      - TZ=Asia/Singapore
      - POSTGRES_DB=gamevault_auth
      - POSTGRES_USER=gamevault_user
      - POSTGRES_PASSWORD=gamevault_pass
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - gamevault

  nacos:
    image: nacos/nacos-server:v2.1.1
    container_name: gamevault_nacos_cloud
    platform: linux/amd64
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=embedded
      - TZ=Asia/Singapore
    volumes:
      - ./docker/nacos/logs:/home/nacos/logs
      - ./docker/nacos/data:/home/nacos/data
    restart: unless-stopped
    networks:
      - gamevault

networks:
  gamevault:
    driver: bridge