server:
  port: 8080

spring:
  application:
    name: gamevault-gateway

  cloud:
    nacos:
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:nacos:8848}
        namespace: ${SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE:prod}
        group: GAMEVAULT_GROUP
        enabled: true
        register-enabled: true
        ip: ${POD_IP:}
      config:
        enabled: false
      import-check:
        enabled: false

    gateway:
      # ==================== 路由配置 ====================
      routes:
        # ==================== 认证服务 ====================
        - id: auth-service
          uri: lb://gamevault-auth
          predicates:
            - Path=/api/auth/**,/.well-known/jwks.json,/api/settings/**,/uploads/**
          filters:
            - StripPrefix=0

        # ==================== Shopping 服务 ====================
        - id: shopping-service
          uri: lb://gamevault-shopping
          predicates:
            - Path=/api/games/**,/api/library/**,/api/cart/**,/api/orders/**,/api/admin/games/**,/api/user/activation-codes/**
          filters:
            - StripPrefix=0

        # ==================== Developer 服务 ====================
        - id: developer-service
          uri: lb://gamevault-developer
          predicates:
            - Path=/api/developer/**
          filters:
            - StripPrefix=0

        # ==================== WebSocket 服务 ====================
        - id: social-websocket
          uri: lb:ws://gamevault-social
          predicates:
            - Path=/ws/info/**,/ws/**
          filters:
            - StripPrefix=0

        # ==================== Social 服务 ====================
        - id: social-service
          uri: lb://gamevault-social
          predicates:
            - Path=/api/conversation/**,/api/friend/**,/api/message/**,/api/file/**
          filters:
            - StripPrefix=0

        # ==================== Forum 服务 ====================
        - id: forum-service
          uri: lb://gamevault-forum
          predicates:
            - Path=/api/forum/**
          filters:
            - StripPrefix=0

        # ==================== Profile 服务 ====================
        - id: profile-service
          uri: lb://gamevault-profile
          predicates:
            - Path=/api/settings/**,/api/profile/**
          filters:
            - StripPrefix=0

        # ==================== OPTIONS 预检兜底处理 ====================
        - id: cors-options
          uri: no://op
          predicates:
            - Method=OPTIONS
          filters:
            - SetResponseHeader=Access-Control-Allow-Origin,*
            - SetResponseHeader=Access-Control-Allow-Methods,GET,POST,PUT,DELETE,OPTIONS,PATCH
            - SetResponseHeader=Access-Control-Allow-Headers,*
            - SetResponseHeader=Access-Control-Allow-Credentials,true
            - SetStatus=200

      # ==================== 全局 CORS 配置 ====================
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '/**':                              # ✅ 改成全局
            allowedOriginPatterns:
              - "http://52.77.169.8:30131"    # ✅ 外网前端
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
              - "http://localhost:3001"
              - "http://127.0.0.1:3001"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

# ==================== Actuator ====================
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes,metrics
  endpoint:
    health:
      show-details: when-authorized

# ==================== 日志配置 ====================
logging:
  level:
    org.springframework.cloud.gateway: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/gamevault-gateway.log
