server:
  port: 8080  # 前端统一入口
  # 生产环境服务器配置
  netty:
    connection-timeout: 30s
    idle-timeout: 60s

spring:
  application:
    name: gamevault-gateway

  cloud:
    nacos:
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:nacos:8848}
        namespace: ${SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE:prod}
        group: ${SPRING_CLOUD_NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
        ip: ${SPRING_CLOUD_NACOS_DISCOVERY_IP:}
        register-enabled: true
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        fail-fast: false
      config:
        enabled: false

    import-check:
      enabled: false

    gateway:
      # 路由配置 - 保持前端接口完全不变
      routes:
        # ==================== 认证服务 ====================
        - id: auth-service
          uri: lb://gamevault-auth
          predicates:
            - Path=/api/auth/**, /.well-known/jwks.json, /api/settings/**
          filters:
            - StripPrefix=0

        # ==================== Shopping 服务 ====================
        - id: shopping-service
          uri: lb://gamevault-shopping
          predicates:
            - Path=/api/games/**,/api/library/**,/api/cart/**,/api/orders/**,/api/admin/games/**,/api/user/activation-codes/**
          filters:
            - StripPrefix=0

        # ==================== Developer 服务 ====================
        - id: developer-service
          uri: lb://gamevault-developer
          predicates:
            - Path=/api/developer/**
          filters:
            - StripPrefix=0

        # ==================== WebSocket 服务（独立配置，优先匹配）====================
        - id: social-websocket
          uri: lb:ws://gamevault-social
          predicates:
            - Path=/ws/info/**,/ws/**
          filters:
            - StripPrefix=0

        # ==================== Social 服务 ====================
        - id: social-service
          uri: lb://gamevault-social
          predicates:
            - Path=/api/conversation/**,/api/friend/**,/api/message/**,/api/file/**
          filters:
            - StripPrefix=0

        # ==================== 论坛服务 ====================
        - id: forum-service
          uri: lb://gamevault-forum
          predicates:
            - Path=/api/forum/**
          filters:
            - StripPrefix=0

        # ==================== 个人资料服务 ====================
        - id: profile-service
          uri: lb://gamevault-profile
          predicates:
            - Path=/api/settings/**,/api/profile/**
          filters:
            - StripPrefix=0

      # 全局跨域配置 - 生产环境

      # 网关超时配置
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s
        pool:
          type: elastic
          max-connections: 100
          max-idle-time: 30s

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: false
    gateway:
      enabled: true
  health:
    livenessState:
      enabled: false
    readinessState:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true

# 日志配置
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: INFO
    reactor.netty: INFO
    org.springframework.cloud.gateway.route: DEBUG
    com.alibaba.cloud.nacos: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/gateway-service.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 1GB