server:
  port: 8082

spring:
  application:
    name: gamevault-shopping

  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
        group: DEFAULT_GROUP
        ip: ${SPRING_CLOUD_NACOS_DISCOVERY_IP:}
      config:
        enabled: false
        import-check:
          enabled: false

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          public-key-location: classpath:certs/rsa-public.pem

  # OAuth2 资源服务器 - JWT 验证
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

  # 数据源配置
  datasource:
    url: jdbc:postgresql://localhost:12000/gamevault_shopping
    username: gamevault_user
    password: gamevault_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  # JPA 配置
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

# 激活码库存配置
activation:
  stock:
    target: 30

# 应用配置
app:
  upload:
    path: uploads
    max-file-size: 100MB
    max-request-size: 100MB
  pagination:
    default-page-size: 20
    max-page-size: 100

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info

# 日志配置
logging:
  level:
    com.sg.nusiss.social: DEBUG
    org.springframework.web: INFO
    org.springframework.messaging: DEBUG