server:
  port: 8082
  # 生产环境服务器配置
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
    accept-count: 100

spring:
  application:
    name: gamevault-shopping

  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: nacos:8848
        namespace: prod
        group: ${SPRING_CLOUD_NACOS_DISCOVERY_GROUP:GAMEVAULT_GROUP}
        ip: ${POD_IP:shopping}
        register-enabled: true
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
      config:
        enabled: false
        import-check:
          enabled: false

  # OAuth2 资源服务器 - JWT 验证
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth:8081
          jwk-set-uri: http://auth:8081/.well-known/jwks.json

  # 数据源配置 - Docker Compose 环境
  datasource:
    url: jdbc:postgresql://postgres:5432/gamevault_shopping
    username: gamevault_user
    password: gamevault_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  # JPA 配置
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
      file-size-threshold: 2MB
      location: /uploads

# 激活码库存配置
activation:
  stock:
    target: 30

# 应用配置
app:
  upload:
    path: /uploads
    max-file-size: 100MB
    max-request-size: 100MB
  pagination:
    default-page-size: 20
    max-page-size: 100

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# 日志配置
logging:
  level:
    root: INFO
    com.sg.nusiss.shopping: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/shopping-service.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 1GB