server:
  port: 8083

spring:
  application:
    name: gamevault-forum

  cloud:
    nacos:
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:nacos:8848}
        namespace: ${SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE:prod}
        group: GAMEVAULT_GROUP
        enabled: true
        register-enabled: true
        ip: ${POD_IP:}
      config:
        enabled: false
      import-check:
        enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/gamevault_forum}
    username: ${SPRING_DATASOURCE_USERNAME:gamevault_user}
    password: ${SPRING_DATASOURCE_PASSWORD:gamevault_pass}
    driver-class-name: org.postgresql.Driver

  # 如果生产环境需要 Redis，取消注释
  # data:
  #   redis:
  #     host: ${SPRING_DATA_REDIS_HOST:redis}
  #     database: 1
  #     port: ${SPRING_DATA_REDIS_PORT:6379}
  #     timeout: 3000ms
  #     lettuce:
  #       pool:
  #         max-active: 8
  #         max-idle: 8
  #         min-idle: 0
  #         max-wait: -1ms

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true

# MyBatis 配置
mybatis:
  mapper-locations: classpath:forum/*.xml
  type-aliases-package: com.sg.nusiss.forum.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

# JWT 配置
jwt:
  secret: "1TuQdaZEWG0U7EiIkrGX1xvbaCJDT7XAsksekHxxFgE="
  expiration: 864000000

# HashId 配置
hashid:
  salt: "forum-backend-2024"

rsa:
  public-key: classpath:certs/public.pem

# 应用配置
app:
  upload:
    path: /app/uploads
    max-file-size: 5MB
    max-request-size: 10MB
  pagination:
    default-page-size: 20
    max-page-size: 100
  auth:
    mock:
      enabled: false

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,nacos-discovery
  endpoint:
    health:
      show-details: when-authorized

# 日志配置
logging:
  level:
    com.sg.nusiss.forum: INFO
    com.sg.nusiss.forum.mapper: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/gamevault-forum.log
#    max-size: 10MB
#    max-history: 30