---
# Nacos PersistentVolumeClaim for logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-logs-pvc
  namespace: gamevault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---
# Nacos PersistentVolumeClaim for data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-data-pvc
  namespace: gamevault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---
# Nacos Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: gamevault
  labels:
    app: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - name: nacos
        image: nacos/nacos-server:v2.1.1
        ports:
        - containerPort: 8848
          name: http
        - containerPort: 9848
          name: grpc
        env:
        - name: MODE
          value: "standalone"
        - name: PREFER_HOST_MODE
          value: "hostname"
        - name: SPRING_DATASOURCE_PLATFORM
          value: "embedded"
        - name: TZ
          value: "Asia/Singapore"
        volumeMounts:
        - name: nacos-logs
          mountPath: /home/nacos/logs
        - name: nacos-data
          mountPath: /home/nacos/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /nacos/v1/console/health/liveness
            port: 8848
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /nacos/v1/console/health/readiness
            port: 8848
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: nacos-logs
        persistentVolumeClaim:
          claimName: nacos-logs-pvc
      - name: nacos-data
        persistentVolumeClaim:
          claimName: nacos-data-pvc

---
# Nacos Service
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: gamevault
  labels:
    app: nacos
spec:
  type: ClusterIP
  ports:
  - port: 8848
    targetPort: 8848
    protocol: TCP
    name: http
  - port: 9848
    targetPort: 9848
    protocol: TCP
    name: grpc
  selector:
    app: nacos
