server:
  port: 8081

spring:
  application:
    name: gamevault-auth

  # 数据源配置
  datasource:
    url: jdbc:postgresql://localhost:12000/gamevault_auth
    username: gamevault_user
    password: gamevault_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  # JPA 配置
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Nacos 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
        group: GAMEVAULT_GROUP
      config:
        server-addr: localhost:8848
        namespace: dev
        group: GAMEVAULT_GROUP
        file-extension: yml
        enabled: false
        import-check:
          enabled: false

# RSA 密钥配置
rsa:
  private-key: classpath:certs/rsa-private.pem
  public-key: classpath:certs/rsa-public.pem

# JWT 配置
app:
  jwt:
    expiration-minutes: 120

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    com.sg.nusiss.auth: DEBUG
    org.springframework.security: DEBUG