server:
  port: 8089
  tomcat:
    max-swallow-size: 100MB
    max-http-form-post-size: 100MB

spring:
  application:
    name: gamevault-social

  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:nacos:8848}
        namespace: ${SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE:prod}
        group: GAMEVAULT_GROUP
        enabled: true
        register-enabled: true
        ip: ${POD_IP:}
      config:
        enabled: false
      import-check:
        enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:certs/rsa-public.pem

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/gamevault_social}
    username: ${SPRING_DATASOURCE_USERNAME:gamevault_user}
    password: ${SPRING_DATASOURCE_PASSWORD:gamevault_pass}

  jpa:
    hibernate:
      ddl-auto: update
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      database: 1
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# MinIO 配置 - 生产环境（重要！）
minio:
  # 内部服务间通信地址
  endpoint: http://minio:9000
  # 外部访问地址（返回给前端的 URL）- 请替换为你的 EC2 公网 IP
  public-endpoint: ${MINIO_PUBLIC_ENDPOINT:http://52.77.169.8:30900}
#  public-endpoint: http://52.77.169.8:30900
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin123}
  bucket-name: gamevault-chat
  image-bucket: gamevault-images
  video-bucket: gamevault-videos
  file-bucket: gamevault-files
  audio-bucket: gamevault-audios

# 文件上传配置
file:
  upload:
    temp-path: ${java.io.tmpdir}/gamevault-uploads
  image:
    max-size: 10485760
    allowed-types: jpg,jpeg,png,gif,webp,bmp,svg
    generate-thumbnail: true
    thumbnail-width: 200
    thumbnail-height: 200
  video:
    max-size: 524288000
    allowed-types: mp4,avi,mov,wmv,flv,mkv,webm,m4v
    generate-cover: true
  document:
    max-size: 20971520
    allowed-types: pdf,doc,docx,xls,xlsx,ppt,pptx,txt,zip,rar,7z
  audio:
    max-size: 52428800
    allowed-types: mp3,wav,aac,flac,ogg,m4a,wma
  chunk:
    size: 5242880
    min-file-size: 10485760
    task-expire-hours: 24
  presigned:
    upload-expire-minutes: 60
    download-expire-hours: 24
  quick-upload:
    enabled: true
  concurrent:
    max-uploads-per-user: 5

# 应用配置
app:
  upload:
    path: uploads
    max-file-size: 100MB
    max-request-size: 100MB
  pagination:
    default-page-size: 20
    max-page-size: 100

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# 日志配置 - 生产环境
logging:
  level:
    com.sg.nusiss.social: INFO
    org.springframework.web: INFO
    org.springframework.messaging: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/gamevault-social.log
#    max-size: 10MB
#    max-history: 30