apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamevault-gateway
  namespace: gamevault
  labels:
    app: gamevault-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamevault-gateway
  template:
    metadata:
      labels:
        app: gamevault-gateway
    spec:
      containers:
        - name: gateway
          image: ${DOCKER_REGISTRY}/gamevault-gateway:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            # Spring Profile - 激活生产环境配置
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            # Nacos 配置
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR
              value: "nacos:8848"
            - name: SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE
              value: "prod"

            # Pod IP（用于 Nacos 注册）
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "1Gi"
          #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gamevault-gateway
  namespace: gamevault
  labels:
    app: gamevault-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gamevault-gateway
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gamevault-gateway-hpa
  namespace: gamevault
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gamevault-gateway
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80