apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamevault-shopping
  namespace: gamevault
  labels:
    app: gamevault-shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamevault-shopping
  template:
    metadata:
      labels:
        app: gamevault-shopping
    spec:
      containers:
        - name: shopping
          image: ${DOCKER_REGISTRY}/gamevault-shopping:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            # Spring Profile - 激活生产环境配置
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            # 数据库配置
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/gamevault_shopping"
            - name: SPRING_DATASOURCE_USERNAME
              value: "gamevault_user"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            # Nacos 配置
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR
              value: "nacos:8848"
            - name: SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE
              value: "prod"

            # Pod IP（用于 Nacos 注册）
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "1Gi"
          #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gamevault-shopping
  namespace: gamevault
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: gamevault-shopping