apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamevault-social
  namespace: gamevault
  labels:
    app: gamevault-social
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamevault-social
  template:
    metadata:
      labels:
        app: gamevault-social
    spec:
      containers:
        - name: social
          image: ${DOCKER_REGISTRY}/gamevault-social:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          env:
            # Spring Profile - 激活生产环境配置
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            # 数据库配置
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/gamevault_auth"
            - name: SPRING_DATASOURCE_USERNAME
              value: "gamevault_user"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            # Nacos 配置
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR
              value: "nacos:8848"
            - name: SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE
              value: "prod"

            # Redis 配置
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"

            # MinIO 配置 - 关键！
            - name: MINIO_PUBLIC_ENDPOINT
              value: "http://52.77.169.8:9000"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD

            # Pod IP（用于 Nacos 注册）
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "1Gi"
          #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gamevault-social
  namespace: gamevault
spec:
  type: ClusterIP
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: gamevault-social